#!/bin/bash

# SVN post-commit hook used to update remote working copy.

REPOS="$1"
REV="$2"

SSH="/usr/bin/ssh"
PATH_REMOTE_DOC_ROOT="/var/www/example.com/htdocs"

$SSH -l <username> <hostname> "cd $PATH_REMOTE_DOC_ROOT && svn up" > /var/svn/project-up.log 2>&1
